### ISSUE TITLE
How much longer should plugins support the wp8 platform?

### ISSUE THREAD

**Issue by brodybits** [cordova/cordova-discuss#37]
Considering the following factors:
- wp8 is "deprecated"
- wp8 requires C# while most Windows 8.1/Windows Phone 8.1/Windows 10 plugins can simply use Javascript
- it is almost impossible to interface wp8 with C/C++ libraries due to the use of Silverlight

Is there any reason for plugins to keep supporting wp8?

**Comment by nikhilkh** [comment]
Every plugin should determine from it's community of users whether it needs to support WP8. From Apache Cordova project, WP8 is in deprecated mode - there are no new releases or work planned. 

Another aspect to note is that cordova-wp8 npm download stats show a steady decline since our deprecation notice:

http://npm-stat.com/charts.html?package=cordova-wp8&author=&from=&to=
