### ISSUE TITLE
Extended LTS release support?

### ISSUE THREAD

**Issue by brodybits** [cordova/cordova-discuss#39]
Constant and rapid evolution is excellent in general but can cause problems for certain users that have to work for years without major upgrades. It would be great to see LTS releases that are supported for ~~at least~~ 3-5 years.

_I would be happy to help as much as I can. I hope some others would be willing to help._

**Comment by nikhilkh** [comment]
This is definitely an interesting idea. We've had a 6 month support policy for releases. It might be a good idea to re-visit if it makes sense. 3-5 years sounds like a big step compared to 6 month that we have - I'm not sure if we have the resources as a community to do something like that.

**Comment by axemclion** [comment]
I think this is a great idea. As I see it, we roughly follow semvers, so would LTS in our case mean we backport bugs and patches to (n-1) versions and release patch versions ?
Also, 3-5 years may seem excessive. Historically, we have been bumping a major version approximately every year. Would that mean we would have to keep 4.0 updated to support the latest platforms ? 

We have added telemetry to the Cordova CLI, and one segment of information we would get will be related to versions. I think that should be a data point we consider, before looking at the idea of LTS.

**Comment by kerrishotts** [comment]
Being a technical writer, I feel the pain of rapid movement on PhoneGap/Cordova. It's not uncommon to be revising early chapters near the end of the book's deadline in order to be compatible with the most recently released version of Cordova (or the core plugins).

I'm certainly not against a longer period of support -- perhaps a year, but 3-5 seems untenable to me (at the moment). I don't see that the community or the present dev team have the resources at the moment to support such a long period of support. Even extending the period of support would create a strain.

Also, I imagine that any LTS would have to be tailored to the platform. For example, iOS would have to be at the low end of the support spectrum, given that Apple stops signing older iOS versions pretty quickly. End-user iOS devices get upgraded reasonably frequently, so there's not a lot of market share to justify a lot of work. Enterprises move a lot more slowly, but I also think they could also afford to pay for any necessary support.

My 2¢ anyway! :-)

**Comment by brodybits** [comment]
Thanks for your responses so far. I have to agree that the 3-5 years would be impractical, at least at this stage since mobile platforms are changing so quickly.

Here is what triggered my desire for 3-5 years: I saw a case where someone had been working on a large, distributed multi-device system for 3 years or so using Cordova 3.x. I quickly recommended upgrading to Cordova 6.x but it would have meant redoing large-scale testing and integration. This is what triggered my idea of LTS in the first place.

Another comment is that LTS means different things to different people:
- OpenSSL LTS releases are supported for at least 5 years [1]
- Ubuntu now supports LTS for 5 years (was 3 years for Desktop in the past) [2]
- NodeJS LTS is "actively maintained" for 18 months then in "maintenance mode" for another 12 months

A further question is what do we mean by LTS? I can think of the following possibilities:
- Security fixes
- Critical bug fixes
- Intermittent failures (I consider this extremely important since they can become a time waster when we least expect it and can pop up at critical stages)
- Platform needs (for example: do y instead of x since iOS 11 broke z)

My idea would be to start with a shorter term such as 12-18 months and increase it over time.

A couple alternative approaches:
- look for corporate sponsorship first (if nobody wants to pay how much obligation should we really have?)
- setup a program with companies that would be willing to actively support LTS releases and sell LTS support services

[1] https://www.openssl.org/policies/releasestrat.html
[2] https://wiki.ubuntu.com/LTS
[3] https://github.com/nodejs/LTS

**Comment by rdesimone** [comment]
For various reasons we are forced to update to the latest development tools (xCode, Android Studio, SDKs, ...). Instead of using resources for LTS, Cordova and core plugins should adapt as fast as possible to the latest tools. If the project is setup nicely, it allows the building for "any" Cordova version. IMO there should be a discussion about extending core plugins (e.g. Crosswalk). Ideally we should come to the point to get verified kits (TACO) with the release of the latest dev tools.

**Comment by brodybits** [comment]
Closing due to lack of interest. I do not recommend starting this kind of program without sufficient backing resources (i.e. sponsoring of enough developer time to actively maintain certain older releases).
